#!/bin/bash

SOURCE=${BASH_SOURCE[0]}
while [ -L "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
  DIR=$( cd -P "$( dirname "$SOURCE" )" >/dev/null 2>&1 && pwd )
  SOURCE=$(readlink "$SOURCE")
  [[ $SOURCE != /* ]] && SOURCE=$DIR/$SOURCE # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
done
SCRIPTDIR=$( cd -P "$( dirname "$SOURCE" )" >/dev/null 2>&1 && pwd )
. $SCRIPTDIR/config.sh

echo " Trav-Scripts Menu: github.com/TheRealAlexV/steamdeck-scripts"
echo "  1) Post Update Init    |   2) SSHd Configuration  |  3) Setup Sleep Inhibitor "
echo "  4) BTRFS Utilities     |     5) Backup Packages   |    6) Restore Packages    "
echo "  7) Setup Joycon Cfgs   |        8) Setup UFW      |   9) Fix Lutris Flatpak   "
echo "  10) Kill Windows Emus  |  11) Fix pipewire Audio  |     12) Sudo NoPasswd     "
echo "  13) auto-cpufreq       |  14) Dock Resolution Fix |          Q) Quit          "
echo -n "B=D: "
read n

case $n in
        1)
            . $FUNCTIONS/post-update-init.sh
            ;;
        2)
            . $FUNCTIONS/sshd.sh
            ;;
        3)
            . $FUNCTIONS/inhibit_sleep.sh
            ;;
        4)
            . $FUNCTIONS/btrfs-optimize.sh
            ;;
        5)
            . $FUNCTIONS/backup-packages.sh
            ;;
        6)
            . $FUNCTIONS/restore-packages.sh
            ;;
        7)
            . $FUNCTIONS/joycons.sh
            ;;
        8)
            . $FUNCTIONS/ufw.sh
            ;;
        9)
            . $FUNCTIONS/fix_lutris.sh
            ;;
        10)
            . $FUNCTIONS/killproton.sh
            ;;
        11)
            . $FUNCTIONS/pipewire_fix.sh
            ;;
        12)
            . $FUNCTIONS/sudo_nopasswd.sh
            ;;
        13)
            . $FUNCTIONS/auto-cpufreq.sh
            ;;
        14)
            . $FUNCTIONS/dock-resolution-fix.sh
            ;;
        15)
            . $FUNCTIONS/fix_krfb.sh
            ;;
        D)
            . $FUNCTIONS/install-dev-tools.sh
            ;;
        q)
            exit
            ;;
        *)
            echo "Thats not an option."
            exit
            ;;
esac